
#include "sdkconfig.h" // generated by "make menuconfig"
#include "driver/i2c.h"
/*#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)
#define SDA_PINs "GPIO_NUM_" STR(CONFIG_ESP_i2c_luz_sda)
#define SCL_PINs "GPIO_NUM_" STR(CONFIG_ESP_i2c_luz_scl)*/

#define SDA_PIN CONFIG_i2c_luz_sda
#define SCL_PIN CONFIG_i2c_luz_scl

#define MAX44009_ADDRESS1 0x4A
#define MAX44009_ADDRESS2 0x4B

void i2c_master_init(i2c_port_t port,double velocidad);
void task_max44009_read_ambient_light(void *valor);

typedef struct{
    float valor;
    char direccion;
    char i2c_port;
}lectura_luz;
void init_max(lectura_luz max);